-- Insert sample articles for Insights tab
-- These are general articles (not user-specific, so user_id is NULL)
-- Run this in your Supabase SQL Editor

INSERT INTO public.insights_articles (user_id, category, title, summary, content, tags, is_personalized, stage)
VALUES
  -- Article 1: Nutrition during pregnancy
  (NULL, 'nutrition', 'Essential Nutrients for a Healthy Pregnancy', 
   'A comprehensive guide to the vitamins and minerals you and your baby need during pregnancy.',
   E'**Key Nutrients for Pregnancy:**\n\n**Folic Acid (400-800 mcg daily)**\nPrevents neural tube defects and supports baby''s brain development.\n- Leafy greens (spinach, kale)\n- Fortified cereals\n- Lentils and beans\n- Citrus fruits\n\n**Iron (27 mg daily)**\nPrevents anemia and supports increased blood volume.\n- Red meat\n- Poultry and fish\n- Beans and lentils\n- Fortified cereals\n- Take with vitamin C for better absorption\n\n**Calcium (1000 mg daily)**\nBuilds baby''s bones and teeth.\n- Milk, yogurt, cheese\n- Leafy greens\n- Fortified plant milks\n- Tofu\n\n**Protein (70-100g daily)**\nSupports baby''s growth and your changing body.\n- Lean meat, poultry, fish\n- Eggs\n- Beans and legumes\n- Nuts and seeds\n- Dairy products\n\n**DHA (200-300 mg daily)**\nSupports baby''s brain and eye development.\n- Fatty fish (salmon, sardines)\n- DHA-fortified eggs\n- Algae-based supplements\n\n**Vitamin D (600 IU daily)**\nSupports bone health and immune function.\n- Sunlight exposure\n- Fortified milk\n- Fatty fish\n- Supplements\n\n**Hydration**\nDrink 8-12 glasses of water daily to support increased blood volume and amniotic fluid.\n\n**Foods to Avoid:**\n- Raw or undercooked meat, fish, eggs\n- Unpasteurized dairy\n- High-mercury fish (shark, swordfish)\n- Excess caffeine (limit to 200mg/day)\n- Alcohol\n\nRemember: A balanced, varied diet is best. Prenatal vitamins help fill nutritional gaps!',
   ARRAY['nutrition', 'vitamins', 'pregnancy-health', 'diet'],
   false, 'pregnancy'),

  -- Article 2: Exercise during pregnancy
  (NULL, 'wellness', 'Safe Exercise During Pregnancy',
   'Stay active and healthy with pregnancy-safe exercises that benefit you and baby.',
   E'**Benefits of Pregnancy Exercise:**\n\n✅ Reduces back pain and swelling\n✅ Improves mood and energy\n✅ Helps you sleep better\n✅ Prepares body for labor\n✅ Speeds postpartum recovery\n✅ Reduces risk of gestational diabetes\n\n**Safe Exercises:**\n\n**Walking (30 minutes daily)**\n- Low-impact, easy to maintain\n- Great for all fitness levels\n- Can continue throughout pregnancy\n\n**Swimming**\n- Supports your weight\n- Reduces swelling\n- Low risk of injury\n- Feels refreshing\n\n**Prenatal Yoga**\n- Improves flexibility\n- Teaches breathing for labor\n- Reduces stress\n- Builds strength\n\n**Pelvic Floor Exercises (Kegels)**\n- Strengthens pelvic muscles\n- Helps prevent incontinence\n- Supports labor and recovery\n- Do 3 sets of 10 daily\n\n**Light Strength Training**\n- Maintains muscle tone\n- Use lighter weights\n- Focus on good form\n- Avoid lying flat after 20 weeks\n\n**Exercise Guidelines:**\n\n⚠️ **Avoid:**\n- Contact sports\n- Activities with fall risk\n- Lying flat on back after 20 weeks\n- Hot yoga or overheating\n- High-altitude activities\n- Scuba diving\n\n✓ **Safe Practices:**\n- Stay hydrated\n- Wear supportive shoes\n- Exercise in cool environment\n- Listen to your body\n- Stop if you feel dizzy or short of breath\n\n**When to Stop & Call Doctor:**\n- Vaginal bleeding\n- Regular contractions\n- Fluid leaking\n- Chest pain\n- Severe headache\n- Calf pain or swelling\n\n**By Trimester:**\n\n**First Trimester:**\n- Continue your routine if already active\n- Start slowly if new to exercise\n- Combat fatigue with rest\n\n**Second Trimester:**\n- Energy returns - great time to exercise!\n- Modify as belly grows\n- Use support belt if needed\n\n**Third Trimester:**\n- Focus on comfort\n- Gentle movements\n- Prepare for labor with pelvic exercises\n\nAlways consult your doctor before starting any exercise program!',
   ARRAY['exercise', 'fitness', 'wellness', 'pregnancy-safe'],
   false, 'pregnancy'),

  -- Article 3: Baby development
  (NULL, 'baby-care', 'Your Baby''s Development Week by Week',
   'Fascinating changes happening with your baby throughout pregnancy.',
   E'**First Trimester (Weeks 1-12):**\n\n**Week 4-5:** Heart starts beating\n**Week 6:** Brain and nervous system forming\n**Week 8:** All major organs present\n**Week 10:** Baby can move (you can''t feel it yet)\n**Week 12:** Fingerprints forming\n\n**Second Trimester (Weeks 13-27):**\n\n**Week 16:** Baby can hear sounds\n**Week 18-20:** You feel first movements!\n**Week 20:** Baby has sleep/wake cycles\n**Week 22:** Taste buds developing\n**Week 24:** Baby responds to voices\n**Week 27:** Eyes can open\n\n**Third Trimester (Weeks 28-40):**\n\n**Week 28:** Baby can dream\n**Week 32:** Practicing breathing movements\n**Week 36:** Lungs nearly mature\n**Week 37:** Full term! Ready to be born\n**Week 40:** Due date (but may come earlier or later)\n\n**Amazing Facts:**\n\n🎵 Baby can recognize your voice by week 25\n👶 Hiccups are common - you''ll feel them!\n🎨 Baby''s personality is already forming\n💤 Baby sleeps 90-95% of the time\n🎶 Playing music can stimulate brain development\n👂 Loud noises may startle baby\n\n**Bonding Before Birth:**\n\n- Talk and sing to baby\n- Play music\n- Gentle belly massage\n- Partner can talk too!\n- Read books aloud\n- Respond to kicks\n\n**Tracking Movement:**\n\nAfter 28 weeks, do daily kick counts:\n- Pick a time when baby is usually active\n- Count 10 movements\n- Should happen within 2 hours\n- Call doctor if movements decrease\n\nEvery pregnancy is unique - your baby is one of a kind! 💕',
   ARRAY['baby-development', 'pregnancy-stages', 'fetal-development'],
   false, 'pregnancy'),

  -- Article 4: Mental health
  (NULL, 'wellness', 'Mental Health During Pregnancy',
   'Taking care of your emotional wellbeing is just as important as physical health.',
   E'**Common Emotional Changes:**\n\n**Mood Swings**\nHormones cause rapid emotional shifts - completely normal!\n- Happens most in first and third trimesters\n- Can go from happy to tearful quickly\n- Usually temporary\n\n**Anxiety**\nWorries about baby, birth, and parenting are common.\n- Health concerns\n- Financial stress\n- Body changes\n- Labor fears\n\n**Pregnancy Depression**\nAffects 10-15% of pregnant women.\n\n**Symptoms:**\n- Persistent sadness\n- Loss of interest\n- Changes in sleep/appetite\n- Difficulty concentrating\n- Feelings of worthlessness\n\n**When to Seek Help:**\n\n⚠️ If symptoms last more than 2 weeks\n⚠️ Interfere with daily life\n⚠️ Thoughts of harming yourself\n⚠️ Panic attacks\n⚠️ Extreme anxiety\n\n**Self-Care Strategies:**\n\n**Physical Care:**\n- Regular gentle exercise\n- Adequate sleep (8-10 hours)\n- Healthy nutrition\n- Prenatal massage\n\n**Emotional Support:**\n- Talk to partner, family, friends\n- Join pregnancy support groups\n- Keep a journal\n- Practice mindfulness\n\n**Stress Management:**\n- Deep breathing exercises\n- Prenatal yoga\n- Meditation apps\n- Calming music\n- Nature walks\n\n**Professional Help:**\n\n✅ Therapist or counselor\n✅ Support groups\n✅ Psychiatrist (safe medications available)\n✅ Pregnancy helplines\n\n**For Partners:**\n\n- Listen without judging\n- Help with household tasks\n- Encourage self-care\n- Attend appointments together\n- Watch for warning signs\n\n**Preparing for Postpartum:**\n\n- Line up support before birth\n- Discuss feelings with doctor\n- Plan for help in early weeks\n- Know postpartum depression signs\n\n**Remember:**\n- Mental health affects physical health\n- Asking for help is strength\n- You deserve support\n- Treatment is safe and effective\n- Your wellbeing matters!\n\nYou''re not alone, and help is available. Taking care of yourself helps your baby too. 💚',
   ARRAY['mental-health', 'wellness', 'anxiety', 'depression', 'self-care'],
   false, 'pregnancy'),

  -- Article 5: Preparing for labor
  (NULL, 'baby-care', 'Labor & Delivery: What to Expect',
   'Understanding the stages of labor and how to prepare for birth day.',
   E'**Signs Labor is Starting:**\n\n**Early Signs (Days to Weeks Before):**\n- Baby "drops" lower\n- More energy (nesting instinct)\n- Weight loss (1-3 lbs)\n- More Braxton Hicks contractions\n\n**Active Labor Signs:**\n- Regular contractions (5-10 min apart)\n- Water breaks (gush or trickle)\n- Bloody show (mucus plug)\n- Lower back pain\n\n**Stages of Labor:**\n\n**Stage 1: Early Labor (Hours to Days)**\n- Cervix dilates 0-6 cm\n- Contractions mild, irregular\n- Stay home, rest, eat light\n- Time contractions\n\n**Stage 2: Active Labor (3-8 hours)**\n- Cervix dilates 6-10 cm\n- Contractions stronger, regular\n- Go to hospital\n- Pain management available\n\n**Stage 3: Transition (30 min - 2 hours)**\n- Cervix fully dilated\n- Most intense contractions\n- May feel pressure to push\n- Almost there!\n\n**Stage 4: Pushing & Birth (Minutes to 3 hours)**\n- Push with contractions\n- Baby is born!\n- Immediate skin-to-skin\n- First breath, first cry\n\n**Stage 5: Placenta (5-30 minutes)**\n- Deliver placenta\n- Mild contractions\n- Stitches if needed\n\n**Pain Management Options:**\n\n**Natural Methods:**\n- Breathing techniques\n- Position changes\n- Massage\n- Warm shower/bath\n- Music, aromatherapy\n\n**Medical Options:**\n- Epidural (most common)\n- Spinal block\n- IV pain medication\n- Nitrous oxide (laughing gas)\n\n**When to Go to Hospital:**\n\n**Call Immediately:**\n- Water breaks\n- Bright red bleeding\n- Severe pain\n- Baby stops moving\n\n**Go to Hospital:**\n- Contractions 5 minutes apart for 1 hour\n- Can''t talk through contractions\n- Feel urge to push\n\n**Hospital Bag Checklist:**\n\n**For You:**\n- ID, insurance cards\n- Birth plan\n- Comfortable clothes\n- Toiletries\n- Phone charger\n- Nursing bras\n- Going home outfit\n\n**For Baby:**\n- 2-3 outfits (newborn & 0-3 month)\n- Blankets\n- Car seat (installed!)\n- Diapers (hospital provides)\n\n**For Partner:**\n- Snacks, drinks\n- Change of clothes\n- Camera\n- Pillow\n\n**Birth Plan Considerations:**\n\n- Pain management preferences\n- Labor positions\n- Who you want present\n- Immediate postpartum wishes\n- Feeding plans\n\n**Remember:**\n- Every labor is unique\n- Stay flexible\n- Trust your body\n- You''ve got this! 💪\n\nYour body knows how to birth your baby. You are stronger than you know!',
   ARRAY['labor', 'delivery', 'birth', 'preparation', 'hospital'],
   false, 'pregnancy'),

  -- Article 6: Postpartum care
  (NULL, 'recovery', 'Postpartum Care: The Fourth Trimester',
   'Taking care of yourself during the first 12 weeks after birth.',
   E'**The Fourth Trimester:**\n\nThe first 12 weeks after birth are a major transition. Your body is healing while adjusting to motherhood.\n\n**Physical Recovery Timeline:**\n\n**Week 1:**\n- Heavy bleeding (lochia)\n- Uterine cramping\n- Breast engorgement\n- Extreme fatigue\n- Soreness (vaginal) or pain (C-section)\n\n**Weeks 2-6:**\n- Bleeding decreases\n- Uterus shrinks to normal size\n- Incision healing (C-section)\n- Hair loss may start (temporary!)\n- Night sweats\n\n**Weeks 6-12:**\n- Body continuing to adjust\n- Hormones stabilizing\n- Energy returning\n- 6-week checkup\n\n**Self-Care Essentials:**\n\n**Physical Care:**\n- Rest when baby sleeps\n- Healthy, frequent meals\n- Stay hydrated (especially if breastfeeding)\n- Gentle movement (walking)\n- Avoid heavy lifting\n\n**Perineal Care:**\n- Ice packs first 24 hours\n- Warm sitz baths\n- Pat dry gently\n- Change pads frequently\n- Use witch hazel pads\n\n**C-Section Care:**\n- Keep incision clean and dry\n- Support when coughing/laughing\n- Avoid stairs when possible\n- No driving for 2 weeks\n- Watch for infection signs\n\n**Emotional Wellbeing:**\n\n**Baby Blues (50-80% of moms):**\n- Crying, mood swings\n- Anxiety, overwhelm\n- Peaks around day 5\n- Resolves in 2 weeks\n\n**Postpartum Depression (10-20%):**\n- Persistent sadness\n- Loss of interest\n- Difficulty bonding\n- Sleep/appetite changes\n- **Seek help if symptoms persist**\n\n**Warning Signs - Call Doctor:**\n\n🚨 Heavy bleeding (soaking pad per hour)\n🚨 Fever over 100.4°F\n🚨 Severe abdominal pain\n🚨 Foul-smelling discharge\n🚨 Red, swollen breasts (mastitis)\n🚨 Painful urination\n🚨 Leg pain/swelling (blood clot)\n🚨 Thoughts of harming yourself/baby\n\n**Nutrition Focus:**\n\n**If Breastfeeding:**\n- Extra 450-500 calories daily\n- Protein-rich foods\n- Calcium sources\n- Omega-3 fatty acids\n- Lots of water\n\n**Recovery Foods:**\n- Iron-rich (red meat, spinach)\n- Fiber (whole grains, fruits)\n- Protein (eggs, fish, beans)\n- Vitamin C (citrus, berries)\n\n**Relationship Changes:**\n\n**With Partner:**\n- Communication is key\n- Share responsibilities\n- Schedule time together\n- Be patient with each other\n\n**Intimacy:**\n- Wait 6 weeks before sex\n- Use contraception\n- May take time to feel ready\n- Communicate openly\n\n**Asking for Help:**\n\n✅ Accept meal offers\n✅ Let others hold baby while you rest\n✅ Ask for specific help\n✅ Join new parent groups\n✅ Talk to other moms\n\n**6-Week Checkup:**\n\nDoctor checks:\n- Healing progress\n- Blood pressure\n- Mental health screening\n- Contraception discussion\n- Return to exercise clearance\n\n**Remember:**\n- Recovery takes time\n- Be gentle with yourself\n- Every day you''re healing\n- You''re doing amazing! ❤️\n\nYou just grew and birthed a human. Give yourself grace and time to heal.',
   ARRAY['postpartum', 'recovery', 'self-care', 'healing', 'fourth-trimester'],
   false, 'postpartum')

ON CONFLICT DO NOTHING;
